import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Keep verification builds separate from a developer’s running local demo.
  distDir:
    process.env.LOCAL_VERIFICATION_BUILD === "1" ? ".next-check" : ".next",
  devIndicators: false,
  headers() {
    // Also cover responses generated by Next before a POST handler runs.
    return ["/api/analyze", "/api/extract-url"].map((source) => ({
      source,
      headers: [
        { key: "Cache-Control", value: "no-store, max-age=0" },
        { key: "Pragma", value: "no-cache" },
      ],
    }));
  },
  outputFileTracingIncludes: {
    "/api/extract-url": ["./.generated/extraction-parser.cjs"],
  },
  logging: { browserToTerminal: false },
  experimental: {
    // The development debug channel otherwise persists document data in IndexedDB.
    reactDebugChannel: false,
  },
};

export default nextConfig;
